modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="biandabiangao"
version="1.0.0"
displayName="biandabiangao"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FuBangkun"
description='''
遇水变答辩糕
'''

[[dependencies.biandabiangao]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




